language: python
python:
 - "2.6"
 - "2.7"
 - "3.3"
env:
 - DJANGO_VERSION=1.4.5
 - DJANGO_VERSION=1.5
install:
 - pip install Django==$DJANGO_VERSION --use-mirrors
 - pip install pep8 --use-mirrors
 - pip install pyflakes --use-mirrors
 - pip install . --use-mirrors
before_script:
 - pep8 ifgy_login
 - pyflakes ifgy_login
branches:
 only:
  - master
script:
  - python setup.py test
matrix:
  exclude:
    - python: "3.3"
      env: DJANGO_VERSION=1.4.3

