language: python
python:
 - "2.6"
 - "2.7"
 - "3.3"
env:
 - DJANGO_VERSION=1.4.3
 - DJANGO_VERSION=1.5
install:
 - pip install Django==$DJANGO_VERSION --use-mirrors
 - pip install . --use-mirrors
 - pip install pep8 --use-mirrors
 - pip install https://github.com/dcramer/pyflakes/tarball/master
 - pip install . --use-mirrors
before_script:
 - "pep8 --exclude=migrations --ignore=E501,E225 src"
 - pyflakes -x W src
branches:
 only:
  - master
script:
  - python setup.py test
matrix:
  exclude:
    - python: "3.3"
      env: DJANGO_VERSION=1.4.3

